### ISSUE TITLE
Create router

### ISSUE THREAD

**Issue by dzsozef13** [dzsozef13/Bottomshelf#4]
Add a router so we can go from login to a site that requires log in.

It also should be able handle all routes we add in future.

**Comment by kos3l** [comment]
This article has some nice theory behind router in MVC. Maybe u know it already joci but im posting here anyway :3 https://medium.com/cook-php/vanilla-php-using-a-simple-route-library-bbe1e6dac054

**Comment by kos3l** [comment]
https://github.com/devcoder-xyz/php-router/tree/master/src also this is a good example of a router

**Comment by kos3l** [comment]
Basically finished, not closing this untill we know 100% it works properly with params and so on

**Comment by dzsozef13** [comment]
Probably needs some guarding in future, but for now it can do what we need:
- serve requests with static or/and dynamic parameters by calling controllers and their functions
- redirect to 404 if the request is illegal
